a8:  Assign08.o StrTab.o StrTab.h
	g++ Assign08.o StrTab.o -o a8
Assign08.o: Assign08.cpp StrTab.cpp
	g++ -Wall -ansi -pedantic -c Assign08.cpp
StrTab.o: StrTab.cpp
	g++ -Wall -ansi -pedantic -c StrTab.cpp
